FROM node:20-slim

ARG API_URL
ENV API_URL=$API_URL
ARG FIREBASE_API_KEY
ENV FIREBASE_API_KEY=$FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ENV FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
ARG FIREBASE_PROJECT_ID
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ARG FIREBASE_STORAGE_BUCKET
ENV FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID
ENV FIREBASE_APP_ID=$FIREBASE_APP_ID
ARG FIREBASE_MEASUREMENT_ID
ENV FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID

COPY . ./

RUN npm install -g serve

RUN npm install
RUN npm run build

CMD ["serve", "-s", "./build"]